name: bloc5
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  # NumPy/pandas/scipy/sklearn + IO parquet
  - numpy=2.2.*
  - pandas=2.2.*
  - scipy=1.13.*
  - scikit-learn=1.5.*
  - pyarrow=16.*
  - fastparquet=2024.*
  # Viz & utils
  - matplotlib=3.8.*
  - pillow=11.1.0
  - seaborn
  - tqdm
  - joblib
  # Jupyter
  - jupyterlab
  - ipykernel
  - pyzmq
  - tornado=6.4.*
  # NLP traditionnel
  - spacy=3.8.*
  # PyTorch GPU (RTX 4060 → CUDA 12.1)
  - pytorch=2.4.1
  - torchvision=0.19.1
  - pytorch-cuda=12.1
  # Outils app/monitoring/pipeline
  - streamlit
  - fastapi
  - uvicorn
  - evidently
  - prefect
  # Paquets HF & dérivés (via pip)
  - pip:
      - transformers==4.41.2
      - tokenizers==0.19.1
      - huggingface_hub==0.23.4
      - accelerate==0.31.0
      - sentence-transformers==2.7.0
      - keybert==0.8.5
